2 Labels V, O

In [2]:
pip install NERDA

In [3]:
from collections import defaultdict
import itertools
# import WhitespaceTokenizer() method from nltk
from nltk.tokenize import WhitespaceTokenizer
# Create a reference variable for Class WhitespaceTokenizer
tk = WhitespaceTokenizer()

d = defaultdict(list)
d['sentences'] = []
d['tags'] = []
t = defaultdict(list)
t['sentences'] = []
t['tags'] = []
test = defaultdict(list)
test['sentences'] = []
test['tags'] = []


In [26]:
def nerda_format(data):
  ner = defaultdict(list)
  for line1,line2 in itertools.zip_longest(*[data]*2):
    sents = []
    tags = []
    tokens = iter(tk.tokenize(line1))
    current_tag = "O"
    for token in tokens:
      if token in line2:
        tags.append("V")
        sents.append(token)
      try:
        if token == "[":
          pass
        elif token == "]":
          pass
        else:
          tags.append(current_tag)
          sents.append(token)
      except StopIteration:
        pass
    ner['sentences'].append(sents)
    ner['tags'].append(tags)
  return ner

In [27]:
with open('dev.txt') as data:
    d = nerda_format(data)
    #d['sentences'] = ner['sentences']
    #d['tags'] = ner['tags']

with open('train.txt') as data:
    t = nerda_format(data)
  #  t['sentences'] = ner['sentences']
  #  t['tags'] = ner['tags']

with open('test.txt') as data:
    test = nerda_format(data)
  #  test['sentences'] = ner['sentences']
  #  test['tags'] = ner['tags']

#print(len(d['sentences']))
#print (d['sentences'][1])
#print (d['tags'][1])

In [28]:
d_total_O = 0
t_total_O = 0
test_total_O = 0

d_total_V = 0
t_total_V = 0
test_total_V = 0


for elem in d['tags']:
  d_total_O += elem.count('O')
  d_total_V += elem.count('V')

for elem in t['tags']:
  t_total_O += elem.count('O')
  t_total_V += elem.count('V')

for elem in test['tags']:
  test_total_O += elem.count('O')
  test_total_V += elem.count('V')




In [29]:
print ('V' + '=' + str(d_total_V + t_total_V + test_total_V))
print ('O' + '=' + str(d_total_O + t_total_O + test_total_O))

V=522
O=4473


In [30]:
import NERDA
training = t
validation = d

In [31]:
print(training.get('sentences')[0])

['थः', 'नं', 'छम्ह', 'शक्तिशाली', 'खः', 'धयागु', 'आत्मविश्वास', 'ज्वनाः', 'ज्वनाः', 'न्ह्याःवःगु', 'न्ह्याःवःगु', 'खनेदु', 'खनेदु']


In [32]:
tag_scheme = [
'V'
]

In [33]:
from NERDA.models import NERDA
model = NERDA(
dataset_training = training,
dataset_validation = validation,
tag_scheme = tag_scheme, 
tag_outside = 'O',
transformer = 'bert-base-multilingual-cased',
hyperparameters = {'epochs' : 11,
                  'warmup_steps' : 10,
                  'train_batch_size': 7,
                  'learning_rate': 0.0001})

Device automatically set to: cuda


Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/681M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/972k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.87M [00:00<?, ?B/s]

In [34]:
model.train()


 Epoch 1 / 11


  0%|          | 0/22 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #6 length 275 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #14 length 164 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #16 length 136 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
  9%|▉         | 2/22 [00:01<00:11,  1.79it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #28 length 131 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 14%|█▎        | 3/22 [00:01<00:09,  2.07it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #38 length 137 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 18%|█▊        | 4/22 [00:01<00:08, 

Train Loss = 0.3707362562417984 Valid Loss = 0.2841259017586708

 Epoch 2 / 11


  0%|          | 0/22 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #6 length 275 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #14 length 164 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #16 length 136 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
  9%|▉         | 2/22 [00:00<00:08,  2.29it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #28 length 131 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 14%|█▎        | 3/22 [00:01<00:07,  2.39it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #38 length 137 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 18%|█▊        | 4/22 [00:01<00:07, 

Train Loss = 0.29869960790330713 Valid Loss = 0.22606059163808823

 Epoch 3 / 11


  0%|          | 0/22 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #6 length 275 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #14 length 164 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #16 length 136 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
  9%|▉         | 2/22 [00:00<00:08,  2.29it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #28 length 131 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 14%|█▎        | 3/22 [00:01<00:07,  2.38it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #38 length 137 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 18%|█▊        | 4/22 [00:01<00:07, 

Train Loss = 0.23390202698382465 Valid Loss = 0.16168118019898733

 Epoch 4 / 11


  0%|          | 0/22 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #6 length 275 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #14 length 164 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #16 length 136 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
  9%|▉         | 2/22 [00:00<00:08,  2.30it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #28 length 131 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 14%|█▎        | 3/22 [00:01<00:07,  2.38it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #38 length 137 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 18%|█▊        | 4/22 [00:01<00:07, 

Train Loss = 0.13980465416203847 Valid Loss = 0.09463414301474889

 Epoch 5 / 11


  0%|          | 0/22 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #6 length 275 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #14 length 164 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #16 length 136 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
  9%|▉         | 2/22 [00:00<00:08,  2.26it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #28 length 131 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 14%|█▎        | 3/22 [00:01<00:08,  2.35it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #38 length 137 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 18%|█▊        | 4/22 [00:01<00:07, 

Train Loss = 0.07991990650242026 Valid Loss = 0.043281723434726395

 Epoch 6 / 11


  0%|          | 0/22 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #6 length 275 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #14 length 164 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #16 length 136 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
  9%|▉         | 2/22 [00:00<00:08,  2.25it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #28 length 131 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 14%|█▎        | 3/22 [00:01<00:08,  2.34it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #38 length 137 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 18%|█▊        | 4/22 [00:01<00:07, 

Train Loss = 0.027957085964523933 Valid Loss = 0.03757332742679864

 Epoch 7 / 11


  0%|          | 0/22 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #6 length 275 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #14 length 164 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #16 length 136 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
  9%|▉         | 2/22 [00:00<00:08,  2.27it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #28 length 131 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 14%|█▎        | 3/22 [00:01<00:08,  2.34it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #38 length 137 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 18%|█▊        | 4/22 [00:01<00:07, 

Train Loss = 0.015119990915991366 Valid Loss = 0.03686079188870887

 Epoch 8 / 11


  0%|          | 0/22 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #6 length 275 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #14 length 164 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #16 length 136 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
  9%|▉         | 2/22 [00:00<00:08,  2.28it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #28 length 131 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 14%|█▎        | 3/22 [00:01<00:08,  2.32it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #38 length 137 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 18%|█▊        | 4/22 [00:01<00:07, 

Train Loss = 0.010832522953437134 Valid Loss = 0.04099197227818271

 Epoch 9 / 11


  0%|          | 0/22 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #6 length 275 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #14 length 164 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #16 length 136 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
  9%|▉         | 2/22 [00:00<00:08,  2.27it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #28 length 131 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 14%|█▎        | 3/22 [00:01<00:08,  2.33it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #38 length 137 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 18%|█▊        | 4/22 [00:01<00:07, 

Train Loss = 0.007633362616285343 Valid Loss = 0.04178515051413948

 Epoch 10 / 11


  0%|          | 0/22 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #6 length 275 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #14 length 164 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #16 length 136 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
  9%|▉         | 2/22 [00:00<00:08,  2.24it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #28 length 131 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 14%|█▎        | 3/22 [00:01<00:08,  2.34it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #38 length 137 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 18%|█▊        | 4/22 [00:01<00:07, 

Train Loss = 0.0060213114616503435 Valid Loss = 0.026875059008792352

 Epoch 11 / 11


  0%|          | 0/22 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #6 length 275 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #14 length 164 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #16 length 136 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
  9%|▉         | 2/22 [00:00<00:08,  2.26it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #28 length 131 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 14%|█▎        | 3/22 [00:01<00:08,  2.36it/s]/usr/local/lib/python3.7/dist-packages/NERDA/preprocessing.py:80: UserWarning: Sentence #38 length 137 exceeds max_len 128 and has been truncated
  warnings.warn(msg)
 18%|█▊        | 4/22 [00:01<00:07, 

Train Loss = 0.003576061847111718 Valid Loss = 0.028334516973700374


'Model trained successfully'

In [35]:
model.evaluate_performance(test)

Level  F1-Score  Precision    Recall
0          V   0.96875        1.0  0.939394
0  AVG_MICRO   0.96875        NaN       NaN
0  AVG_MICRO   0.96875        NaN       NaN

In [37]:
#text= [['अझ', 'वृहद', 'कथं', 'धायेगु', 'खःसा', 'थ्व', 'विज्ञान', 'ब्रह्माण्ड', 'गथे', 'सनाच्वंगु', 'दु', 'धका', 'स्वयेत','याइगु', 'प्रकृतिया', 'साधारण', 'एनालाइसिस', 'ख']]
print(model.predict([test['sentences'][1]]))
print(test['tags'][1])

[['O', 'O', 'O', 'O', 'O', 'V', 'O', 'O', 'O', 'V', 'O', 'V', 'O', 'O', 'O', 'V', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'V', 'O', 'V', 'O', 'O']]
['O', 'O', 'O', 'O', 'O', 'V', 'O', 'O', 'O', 'V', 'O', 'V', 'O', 'O', 'O', 'V', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'V', 'O', 'V', 'O', 'O']


In [39]:
## Getting the confusion matrices for every test sentence

from sklearn.metrics import confusion_matrix
y_true = test['tags']
for n in range (len(test['tags'])):
  y_pred = []
  y_pred = model.predict([test['sentences'][n]])[0]
  #print(y_true[n])
  #print(y_pred)
  print(confusion_matrix(y_true[n], y_pred, labels=["V", "O"]))

[[ 2  0]
 [ 0 26]]
[[ 6  0]
 [ 0 23]]
[[ 4  0]
 [ 0 11]]
[[ 3  0]
 [ 0 22]]
[[ 2  1]
 [ 0 31]]
[[ 2  0]
 [ 0 11]]
[[ 3  0]
 [ 0 16]]
[[ 2  0]
 [ 0 13]]
[[ 2  1]
 [ 0 21]]
[[ 1  0]
 [ 0 12]]
[[ 1  0]
 [ 0 18]]
[[ 2  0]
 [ 0 23]]
[[ 1  0]
 [ 0 15]]


In [40]:
# Sum up the 6by6 confusion matrix result in every test sentence
import numpy as np
from sklearn.metrics import confusion_matrix
y_true = test['tags']
d = np.zeros((2,2))
for n in range (len(test['tags'])):
  y_pred = []
  y_pred = model.predict([test['sentences'][n]])[0]
  #print(y_true[n])
  #print(y_pred)
  d += confusion_matrix(y_true[n], y_pred, labels=["V", "O"])
print(d)

[[ 31.   2.]
 [  0. 242.]]
